### ISSUE TITLE
自荐个人博客

### ISSUE THREAD

**Issue by SamanthaWangdl** [timqian/chinese-independent-blogs#1080]
https://rhuen.netlify.app/
个人博客从大一到大四，关注我个人生活工作成长，未来会围绕我去瑞士留学工作的心得感悟。

**Comment by yzqzss** [comment]
本项目的[收录要求](https://github.com/timqian/chinese-independent-blogs#%E4%BB%80%E4%B9%88%E6%98%AF%E7%8B%AC%E7%AB%8B%E5%8D%9A%E5%AE%A2)是：「拥有自己的域名」，虽然允许收录 github.io 这类的公共域名，但是还没有收录 netlify.app 这类公共域名的先例。  
不过依您的博客质量肯定是可以收录的。  

@timqian 你来判定一下吧。

**Comment by kang8** [comment]
这个 blog 确实很棒，只是没有 RSS 有一点遗憾。 @SamanthaWangdl 后面有机会支撑 [RSS](https://en.wikipedia.org/wiki/RSS) 吗？

**Comment by timqian** [comment]
@yzqzss 我觉得用子域名的只要不是采集站可以收录

**Comment by SamanthaWangdl** [comment]
> ### **[kang8](/kang8) ** commented [2 days ago](#issuecomment-1176945273) •

其实是有的，我原本以为没人看，所以给关掉了，我现在可以配置上RSS。

**Comment by SamanthaWangdl** [comment]
> 

RSS已经配置好了。见网页右下角。

**Comment by kang8** [comment]
@SamanthaWangdl 感谢你能支持 RSS。

不过你 RSS 内容中 item 下的 link tag 有些问题，导致我使用的 [RSS 客户端](https://netnewswire.com/) 无法解析：
![image](https://user-images.githubusercontent.com/36906329/178128608-3b6829a7-66b4-41bc-a0f3-332a97e8d310.png)

在 RSS 规范中，item 下的 link tag 提供的是绝对路径而不是相对路径。[source](https://www.rssboard.org/rss-specification#requiredChannelElements:~:text=to%20Quit%20Sinking-,link,-The%20URL%20of)
![image](https://user-images.githubusercontent.com/36906329/178128678-00336f4d-2942-4f72-b830-43a2c38db553.png)

如果能更正下就太棒了。
