### ISSUE TITLE
【🚀 自推博客和GitHub仓库】

### ISSUE THREAD

**Issue by cubxxw** [timqian/chinese-independent-blogs#1158]
我的博客（🏠 地址是：[http://nsddd.top](http://nsddd.top)），记录的都是自己的学习笔记，摘选的是仓库中的精选文章
[菜鸟的成长手册https://github.com/3293172751/cs-awesome-Block_Chain](https://github.com/3293172751/cs-awesome-Block_Chain)。这个仓库记录着📚 菜鸟成长手册🚀 CS系列 、web系列 、BlockChain系列、Golang系列💡......
![image](https://user-images.githubusercontent.com/86140903/192933884-486a2c0b-e056-4ca0-9134-f0035b6ab9d7.png)
希望大家能多多关注😘

**Comment by linlinzzo** [comment]
博客404了。

**Comment by yaoji123000** [comment]
博客挂了

**Comment by cubxxw** [comment]
不好意思，现在博客恢复了
@linlinzzo @yaoji123000

**Comment by yaoji123000** [comment]
这是来自QQ邮箱的自动回复邮件。
您好，邮件已收到，当我登录邮箱时会第一时间回复，紧急邮件请致电与我联系或添加微信与我联系，工作微信:zllx000000000000000(15个0)
