### ISSUE TITLE
列表中的 RSS 订阅数有点小，完全看不清

### ISSUE THREAD

**Issue by tiezhudotwang** [timqian/chinese-independent-blogs#1571]
如图：
![image](https://github.com/timqian/chinese-independent-blogs/assets/126638121/55363ba1-99bb-4be8-a575-e4fde9b0030a)

**Comment by timqian** [comment]
这个挺头疼的，试过一些方式，没找到好办法让这个 button 显示的美观一些。之前试过固定宽度，但因为订阅数不同整个 button 长宽比不同，会有变形。欢迎 PR
> PS 截图好看
