### ISSUE TITLE
Follower count not right

### ISSUE THREAD

**Issue by timqian** [timqian/chinese-independent-blogs#1603]
E.g. For [this blog](https://feeds.pub/feed/https%3A%2F%2Fhutusi.com%2Ffeed.xml), the follower count is > 200, but in readme, it is -1

-1 | 胡涂说 | https://hutusi.com/

**Comment by drewduong** [comment]
I can help with that!

**Comment by yzqzss** [comment]
是 feeds.pub 问题哈哈。 @timqian 

向 https://api.feeds.pub/graphql 请求

```json
{
        f196: feed(id: "https://lyric.im/feed/rss.xml") {
        followerCount
      }
}
```

这个 feed 的数据时，会因为源站超时导致 API 返回空响应的 HTTP 502，然后

https://github.com/timqian/chinese-independent-blogs/blob/4bd19f8fa19ce9aff0e6d8ebfc22147a9980366d/script.js#L24

与它同一批 pageSize 里的博客就全变成默认的 -1 了。

https://github.com/timqian/chinese-independent-blogs/blob/4bd19f8fa19ce9aff0e6d8ebfc22147a9980366d/script.js#L16

**Comment by yzqzss** [comment]
e79de2a327ba9137d683c4df346454e9142fb81e 把 lyric 的有问题的旧 feed 链接换了。

**Comment by timqian** [comment]
@yzqzss 赞！

**Comment by timqian** [comment]
cc @hutusi

**Comment by hutusi** [comment]
👍
