### ISSUE TITLE
计算机与生活的艺术

### ISSUE THREAD

**Issue by jrtx0** [timqian/chinese-independent-blogs#1627]
博客名称：计算机与生活的艺术
链       接：https://jrtx.site
RSS feed：https://jrtx.site/feed.xml
标       签：计算机, 生活

**Comment by Ekkone** [comment]
> 博客名称：计算机与生活的艺术链 接：https://jrtx.siteRSS订阅：https://jrtx.site/feed.xml标 签：计算机, 生活

RSS订阅现在失效了吗
