### ISSUE TITLE
README.md 原本的栏目被吞了

### ISSUE THREAD

**Issue by HowieHz** [timqian/chinese-independent-blogs#1742]
[什么是独立博客](https://github.com/timqian/chinese-independent-blogs/tree/master?tab=readme-ov-file#%E4%BB%80%E4%B9%88%E6%98%AF%E7%8B%AC%E7%AB%8B%E5%8D%9A%E5%AE%A2)
[如何提交](https://github.com/timqian/chinese-independent-blogs/tree/master?tab=readme-ov-file#%E5%A6%82%E4%BD%95%E6%8F%90%E4%BA%A4)
[为什么要收集这张列表](https://github.com/timqian/chinese-independent-blogs/tree/master?tab=readme-ov-file#%E4%B8%BA%E4%BB%80%E4%B9%88%E8%A6%81%E6%94%B6%E9%9B%86%E8%BF%99%E5%BC%A0%E5%88%97%E8%A1%A8)

这几个栏目都被吞了，找历史 commit 还能找到，其他分支也可以找到，但是主分支没有了

**Comment by timqian** [comment]
看起来是达到了github repo 展示 readme 限制，要到 https://github.com/timqian/chinese-independent-blogs/blob/master/README.md 才能看到全部。另外因为 feeds.pub 挂了，follower 数量也都不对，后面考虑改一下 readme 格式

**Comment by HowieHz** [comment]
> 看起来是达到了github repo 展示 readme 限制，要到 https://github.com/timqian/chinese-independent-blogs/blob/master/README.md 才能看到全部。另外因为 feeds.pub 挂了，follower 数量和链接也都不对，后面考虑改一下 readme 格式

感谢回复。
这样的话要不把这个表格单独移动到另一个 markdown 文件，然后 README.md 中做个超链接链接过去www

**Comment by ccbikai** [comment]
> 看起来是达到了github repo 展示 readme 限制，要到 https://github.com/timqian/chinese-independent-blogs/blob/master/README.md 才能看到全部。另外因为 feeds.pub 挂了，follower 数量和链接也都不对，后面考虑改一下 readme 格式

https://substats.swo.moe/ 可以查到 feedly 和 inoreader 的订阅数

**Comment by gxr404** [comment]
github markdown有500k的长度限制，master的已经超了，什么都不改把表格空格去掉 小于500k就能展示全
官方： https://github.com/orgs/community/discussions/23920#discussioncomment-4530804

**Comment by imdong** [comment]
可以改成，readme 不再显示表格，改成 page.github.io 去展示，甚至可以根据 scv 实时生成，还可以加入搜索等逻辑。

**Comment by yzqzss** [comment]
https://github.com/timqian/chinese-independent-blogs/commit/5113f7ccbf82e78159be5c94fd9d7e499cfca479

已将 README.md 大小从 524K 降低到 156K 。
