### ISSUE TITLE
添加 opml 订阅

### ISSUE THREAD

**Issue by ImSingee** [timqian/chinese-independent-blogs#178]
例如 https://github.com/RSS-Renaissance/awesome-blogCN-feeds

**Comment by timqian** [comment]
https://github.com/timqian/chinese-independent-blogs/issues/58#issuecomment-548827895
有热心网友写过一个脚本，回头加到github action里。
也欢迎pr～

**Comment by ImSingee** [comment]
> [#58 (comment)](https://github.com/timqian/chinese-independent-blogs/issues/58#issuecomment-548827895)
> 有热心网友写过一个脚本，回头加到 github action 里。
> 也欢迎 pr～

#179 在 Github Action 中添加了
