### ISSUE TITLE
「五分钟学算法」是有 RSS 的

### ISSUE THREAD

**Issue by ImSingee** [timqian/chinese-independent-blogs#214]
源 URL：https://www.cxyxiaowu.com
RSS 地址：https://www.cxyxiaowu.com/feed

**Comment by Seven-Steven** [comment]
https://github.com/timqian/chinese-independent-blogs/blob/12072705b34cf313ff80df969fd875e30aec9bea/blogs-original.csv#L179

**Comment by Seven-Steven** [comment]
> https://github.com/timqian/chinese-independent-blogs/blob/12072705b34cf313ff80df969fd875e30aec9bea/blogs-original.csv#L179

`blogs-original.csv` 文件中好像写的是 sitemap, 笔误?

**Comment by ImSingee** [comment]
sitemap 是给搜索引擎看的， /feed 这里是正确的 RSS

@timqian 话说为什么 README.md 没有改

**Comment by Seven-Steven** [comment]
哈哈哈我发现自己的博客 RSS 也没有被整理进 README.md, 
[blogs-original.csv #L242](https://github.com/timqian/chinese-independent-blogs/blob/12072705b34cf313ff80df969fd875e30aec9bea/blogs-original.csv#L242)

**Comment by timqian** [comment]
> sitemap 是给搜索引擎看的， /feed 这里是正确的 RSS
> 
> @timqian 话说为什么 README.md 没有改

需要改下 csv，readme 是csv生成的

**Comment by ImSingee** [comment]
> > sitemap 是给搜索引擎看的， /feed 这里是正确的 RSS
> > @timqian 话说为什么 README.md 没有改
> 
> 需要改下 csv，readme 是csv生成的

我看 csv 已经改了但是 README.md 没有变

**Comment by Seven-Steven** [comment]
@ImSingee  csv 没改呀兄弟 
https://github.com/timqian/chinese-independent-blogs/blob/12072705b34cf313ff80df969fd875e30aec9bea/blogs-original.csv#L179
![image](https://user-images.githubusercontent.com/13358658/70487323-ebb2d500-1b2f-11ea-87e8-78d987d8670b.png)

**Comment by ImSingee** [comment]
但是 README 里面连这个 sitemap 都没有…

> @ImSingee csv 没改呀兄弟
> 
> https://github.com/timqian/chinese-independent-blogs/blob/12072705b34cf313ff80df969fd875e30aec9bea/blogs-original.csv#L179
> 
> 
> ![image](https://user-images.githubusercontent.com/13358658/70487323-ebb2d500-1b2f-11ea-87e8-78d987d8670b.png)
