### ISSUE TITLE
script.js 有一定的问题

### ISSUE THREAD

**Issue by ImSingee** [timqian/chinese-independent-blogs#218]
当出现以下情形时 script.js 脚本无法正常检测到变化而导致 README.md 错误

1. 【重要】第一次提交时没有 RSS 地址而后来又有了

    此时因 blogs 文件夹下对应站点的 JSON 文件存在不会被认为是新的博客，而因 JSON 文件内的 subscribers 字段为空而导致此站点依然会被认定为「没有 RSS 的博客」

2. RSS 地址变更

    此时不会检测新的 RSS 地址所对应的数据

3. 应当加入一定时间后的自动更新

    因订阅数据会有所变动，因此隔一段时间拉取新的数据在一定程度下是必要的

**Comment by timqian** [comment]
1, 2 两个问题在 #222 中解决了

第三个问题, 感觉可以再加一个定时任务, 比如每天 update 其中 5 个 feed 的阅读数并标记时间(比较安全, 不容易被 feedly ban)

这样每隔个把月这个列表数据就会更新一回
