### ISSUE TITLE
希望能把掺杂政治的踢出去，技术就是技术

### ISSUE THREAD

**Issue by assad2008** [timqian/chinese-independent-blogs#22]

**Comment by wziwen** [comment]
第三个 编程随想的博客 , 以编程的名义论政治也就算了, 歧视辱骂也能加进来?
是没有点进去看过就直接加了? 心理变态喜欢被骂中国猪还是支持所谓的言论自由?
如果觉得这是言论自由, 我很乐意自由问候你家祖宗

**Comment by wziwen** [comment]
是有点生气过头, 言语过激, 抱歉.

**Comment by HXHL** [comment]
中文独立博客列表,为什么只能有技术类?

**Comment by falseen** [comment]
独立博客传递的是信息与思想，不止是技术。在github上，没必要自我阉割。

**Comment by skygate2012** [comment]
我说怎么没有编程随想的博客，原来已经有太监自阉了。

**Comment by yzqzss** [comment]
编程随想毕竟已经停更许久了，恐怕以后也不会更新了。现在的状况与3年前这个 issue 刚开时不同。

抛开所谓的政治不谈，虽然精神上编程随想可能确实属于独立博客，但重新加回来还是有点小不妥。

1. 博客不再更新;
2. 托管在 blogspot ，无独立域名。

---
其他政治类的博客我不知道情况。

**Comment by GeeLaw** [comment]
> 但我还是更喜欢独立博客，因为有属于自己的域名，因为可以自由地排版，自由地说话。

介绍文档里有这句话，表明“自由地说话”是宗旨之一，因此政治博客本应占有一席之地。因为“敏感”而不收录，完全背离了这个项目的初衷。

> @yzqzss 托管在 blogspot ，无独立域名。

很多现在位于列表中的博客都是 github.io 域名下的，也有 netlify.app 下的，“独立域名说”作为标准恐怕不好。

> @yzqzss 博客不再更新;

有传言编程随想的作者已经被采取强制措施，因此删除似乎不妥，而且“博客死亡的标志是不再可访问，而不是不再更新”。

**Comment by yzqzss** [comment]
@GeeLaw 好的，我被说服了，那我个人的意见是同意收录。
