### ISSUE TITLE
建议有空的时候再整理一下，有些网站已经访问不了了

### ISSUE THREAD

**Issue by Kylelkh** [timqian/chinese-independent-blogs#522]

**Comment by Phuker** [comment]
赞同，另外一些 `http://` 网站可以使用 HTTPS 正常访问，建议改成 `https://`

**Comment by yzqzss** [comment]
我自己已经整理好了一部分，过几天放假（28号之后）我pr上来。包括：域名迁移的，换博客程序导致feed地址变更的，关站的，http(s)变更的

**Comment by linlinzzo** [comment]
会定期整理。
