### ISSUE TITLE
前一百已经消失的网站

### ISSUE THREAD

**Issue by wenyurush** [timqian/chinese-independent-blogs#535]
4	site:http://calvin1978.blogcn.com	"http_code:	000"
8	site:http://www.ideawu.net/blog	"http_code:	404"
11	site:https://zeove.com/	"http_code:	000"
51	site:https://typeblog.net/	"http_code:	404"
79	site:https://blog.biezhi.me	"http_code:	000"
84	site:http://www.fengtang.com/blog/	"http_code:	000"
98	site:https://kenengba.com/	"http_code:	000"

其他200，但是不确定内容对的

**Comment by nobodxbodon** [comment]
刚用 python 的 requests 取了 status_code，除了 200 和 404，有不少其他码但似乎浏览器访问没问题。
@wenyurush 请问之前是如何获取的返回码？
另外，至少此两项可以访问（国外）：
```
84 site:http://www.fengtang.com/blog/	"http_code: 000"
98 site:https://kenengba.com/	"http_code: 000"
```

**Comment by wenyurush** [comment]
> 刚用 python 的 requests 取了 status_code，除了 200 和 404，有不少其他码但似乎浏览器访问没问题。
> @wenyurush 请问之前是如何获取的返回码？
> 另外，至少此两项可以访问（国外）：
> 
> ```
> 84 site:http://www.fengtang.com/blog/	"http_code: 000"
> 98 site:https://kenengba.com/	"http_code: 000"
> ```

果真是我大意了，当时直接测试的，忘了考虑fq的问题

```
time cat url.txt| parallel --eta  -j500 --joblog job.log curl --silent -o {}.$(date +%Y-%m-%d).log  --retry 5 --max-time 20 --connect-timeout 5 --write-out site:{}\'\\\nhttp_code:\\\t%{http_code}\\\nremote_ip:\\\t%{remote_ip}\\\nsize_request:\\\t%{size_request}\\\nsize_header:\\\t%{size_header}\\\nsize_download:\\\t%{size_download}\\\nspeed_download:\\\t%{speed_download}\\\ntime_namelookup:\\\t%{time_namelookup}\\\ntime_connect:\\\t%{time_connect}\\\ntime_total:\\\t%{time_total}\\\n\\\n\' --location --max-redirs 5 --user-agent \"`shuf -n 1 user-agents.txt`\" {} >> net_quality.log

```
完整的结果在

https://github.com/wenyurush/Test_site_status/blob/main/net_quality.log
