### ISSUE TITLE
重复的项

### ISSUE THREAD

**Issue by nobodxbodon** [timqian/chinese-independent-blogs#550]
ngzhio：
![Screen Shot 2021-02-10 at 9 16 48 AM](https://user-images.githubusercontent.com/392497/107546163-e95b6900-6b80-11eb-87ef-a61491d386cf.png)
另外，不知有无工具检查断链、重复等等问题？也许可以集成到 CI，辅助维护？

**Comment by yzqzss** [comment]
@nobodxbodon 这个重复的项是因为这个博客一开始叫 Hszhakka ，后来改名&域名成 Ngzhio。
但博主只是在项目里追加了 Ngzhio 这一行，没有删除原本 Hszhakka 这一行。

导致 #544 在维护坏链时把没有被删除的 Hszhakka 改成了 目前的Hszhakka。所以就重复了…

马上我提交个pr。

**Comment by nobodxbodon** [comment]
@yzqzss 神速啊。刚用这个python脚本查了一下，还有个网址 `https://raincorn.top/` 重复：
```python
import csv, re

所有网址 = set()

with open('blogs-original.csv', newline='') as csvfile:
    各行 = csv.reader(csvfile, delimiter=',', quotechar='|')
    for 行 in 各行:
        网址 = 行[1].strip()
        if 网址 in 所有网址:
            print(网址)
        else:
            所有网址.add(网址)
```

**Comment by nobodxbodon** [comment]
又用博客名查了一下重，发现另两个：
```
炸裂志
the5fire的技术博客
```

**Comment by nobodxbodon** [comment]
@timqian 请看上面两楼，还有几项重复的没有处理。
