### ISSUE TITLE
竟然没有 justyy.com?

### ISSUE THREAD

**Issue by DoctorLai** [timqian/chinese-independent-blogs#577]
本人就是 justyy.com 的博主。。在英国。。写博客近十年。。
https://justyy.com

**Comment by plut0x399** [comment]
自己提交啊
顺便提一句，你网站内容真 **挺XX** 的

**Comment by plut0x399** [comment]
看半天都不知道你在写什么

**Comment by plut0x399** [comment]
![image](https://user-images.githubusercontent.com/81515530/115391997-a9fd6880-a212-11eb-893f-5c7f405af098.png)

还“竟然没有”？真拿自己当个东西

**Comment by DoctorLai** [comment]
你这 github 这个月刚注册的吧。看不懂就对了。

**Comment by Pluto0x999** [comment]
> 你这 github 这个月刚注册的吧。看不懂就对了。

你脑子这个月刚买的吧

**Comment by Pluto0x999** [comment]
你以为自己什么玩意啊啊？

**Comment by Pluto0x999** [comment]
Reply啊 @DoctorLai

**Comment by DoctorLai** [comment]
哟 看把你激动的

**Comment by Pluto0x999** [comment]
https://github.com/timqian/chinese-independent-blogs/issues/649

**Comment by timqian** [comment]
添加博客可以提交 PR 哈
