### ISSUE TITLE
没有 RSS 或者 RSS 有问题的博客们

### ISSUE THREAD

**Issue by timqian** [timqian/chinese-independent-blogs#59]
目前本表仅支持 RSS 可正常订阅的博客, 考虑支持没有 RSS 的博客之前, 需要改下 `./script.js`

- 云大数据社区, http://leozzy.com/, http://leozzy.com/, 编程；大数据；云计算
- 老码农不上班, https://huangwenwei.com, https://huangwenwei.com, 编程; 读书; 区块链;
- EasyLinkerBlog, https://blog.ezlinker.cn, https://blog.ezlinker.cn/feed/, 编程; Erlang;

**Comment by lotosbin** [comment]
没有RSS可以到 rsshub 提交issue，来采集RSS
#r
