### ISSUE TITLE
关于博客被删除的疑问

### ISSUE THREAD

**Issue by Xc1Ym** [timqian/chinese-independent-blogs#821]
您好：
请问我早上刚通过PR，为什么actions就把我删掉了😂
![image](https://user-images.githubusercontent.com/29765332/139791068-1e5a8b7c-8b52-4abd-8558-f932620a29c6.png)

**Comment by yzqzss** [comment]
您在 `https://xdym11235.com` 后面的逗号（即第二个逗号）使用的是中文逗号`，`。
应使用英文半角逗号`,`。

**Comment by Xc1Ym** [comment]
非常抱歉，未能注意标点格式，稍后我将重新提交PR，感谢回复。
