### ISSUE TITLE
收录的链接部分内容不是博客

### ISSUE THREAD

**Issue by user12138** [timqian/chinese-independent-blogs#868]
例如包含vpn字样的看起来都不是博客，还请定时检查列表里链接指向网站的内容

**Comment by yzqzss** [comment]
筛出来4个链接：
https://wall101.com/ （广告站）
https://www.vpndada.com/ （广告站）
https://wallvpn.com/ （广告站）
https://www.duyaoss.com/ （这个质量相对好些，看起来有些原创内容，不是纯广告）

**Comment by renbaoshuo** [comment]
@yzqzss duyaoss.com 是一个很知名的机场测速博客吧...

个人认为这个不算广告
