### ISSUE TITLE
建议生成一个域名列表.txt

### ISSUE THREAD

**Issue by bcaso** [timqian/chinese-independent-blogs#924]
这样使用 google可编程搜索引擎(cse.google.com) 的用户可以直接批量导入了。(格式有要求)

举例：https://github.com/bcaso/Google-Chinese-Results-Whitelist/blob/main/whitelists/domain_name.txt

以及对应建起的自定义搜索引擎：https://cse.google.com/cse?cx=e9a1e480e37a86080&q=

同时，还建议各位的博主将类别层次分得清晰些，如: 脚本之家

教程类：工商银行app怎么查卡号?工商银行app查卡号方法 https://www.jb51.net/softjc/808624.html

软件下载类：https://www.jb51.net/softs/575886.html

脚本之家的教程质量不高，所以，我只添加他的软件下载类别到我的白名单中。规则：`*.jb51.net/softs*`

有域名列表.txt 后，使用 uBlacklist 白名单的用户也可以一键订阅。

我整理的白名单：https://github.com/bcaso/Google-Chinese-Results-Whitelist

**Comment by yzqzss** [comment]
> 建议生成一个域名列表

您可在 blogs-original.csv 中提取域名数据。

**Comment by bcaso** [comment]
提取是一方面，订阅是另一方面。

uBlacklist 支持订阅 txt 文件，且定时更新。

**Comment by bcaso** [comment]
cse.google.com 支持上传 xml 列表。

**Comment by bcaso** [comment]
我相信各位的博客都很有价值，如果能在搜索引擎(uBlacklist txt 白名单，cse.google.com xml 名单) 中搜索到就更好了。

**Comment by ricepeak** [comment]
今天刚好有这个想法，来看果然有人提过了，楼主做了这样的搜索吗😁
