### ISSUE TITLE
独立博客收录标准问题

### ISSUE THREAD

**Issue by taoso** [timqian/chinese-independent-blogs#998]
当前并没有明确的收录标准。README 文件中只说了独立博客的定义：

> 拥有自己的域名
> 作者本人原创内容

我个人感觉以上作为收录标准有点宽泛。我在电报群也看到一些收录请求。其中有两类我认为不应该收录。
1. **伪原创类**
此类多为抓取别人的内容，然后稍加改动后骗取搜索引擎收录，从而获取流量收益。
典型代表为<https://t.me/indieBlogs/12582>
2. **内容聚合类**
此类连**伪原创**处理都不做，直接抓取别人的内容，还美其名曰好文推荐。
典型代表为<https://t.me/indieBlogs/14011>

为此，我建议制定一组更加明确的收录标准。私以为最核心的规则如下：
1. 必须是**独立**网站
关于独立博客的标准，之前也在群里有过[讨论](https://t.me/indieBlogs/12668)。原则上应该使用独立的域名。
2. 必须是**原创**内容
所谓原创，应该是个人经验、知识，或者情感的表达。原创的内容应该是个性化的。像是转载这一类的形式都不能称之为原创。

如果明确了收录标准，那么该如何执行呢？我建议引入人工审核机制。我们可以按照一定规则确定一组原创作者做为审核人。如果有新的博客收入请求，审核人需要大致浏览申请人博客的内容质量。如果符合收录标准才能批准收录。最好是由多人同时批准才允许收录。为了避免审核权力被滥用，审核人需要写明批准或者拒绝的原因。

**Comment by xuwillie** [comment]
> 关于「独立网站」我这里有一些想法。
> 
> * [x]  没有平台的推荐算法
> * [x]  属于自己的域名
> * [x]  自由地排版
> * [x]  自由地说话
> 
> 没有域名，但其他功能都满足时，我觉得也算是独立网站。不过其他的情况大概就比较微妙了。

包含于 `Public Suffix List` 的免费子域名服务的如`github.io` `gitlab.io`等也可以考虑

**Comment by taoso** [comment]
> 包含于 `Public Suffix List` 的免费子域名服务的如`github.io` `gitlab.io`等也可以考虑

应该考虑，好多博客确实使用`github.io`子域名。但感觉`Public Suffix List`的范围太广了，最好是先明确少数常用域名前缀。

我个人建议还是尽量避免使用这类子域名。因为这类平台很容易被审查机构屏蔽，最典型的就是`blogspot.com`和`wordpress.com`前缀，在中国大陆均无法正常访问。

独立网站最好使用独立域名。即便被封，也不会影响其他域名。

**Comment by taozuidesongshu** [comment]
关于「独立网站」我这里有一些想法。

博客的排序,应该由用户对博客的满意程度,点赞或踩,来决定
垃圾博客的清理,随着时间推移必定有些垃圾博客混入其中,建议每过一定时间,清理掉末尾的博客链接,腾出地方

没有域名，但其他功能都满足时，我觉得也算是独立网站 。如 github.io

**Comment by linlinzzo** [comment]
via https://github.com/zh-blogs/blog-daohang#%E5%8D%9A%E5%AE%A2%E6%94%B6%E5%BD%95%E6%A0%87%E5%87%86%E6%98%AF%E4%BB%80%E4%B9%88

**Comment by wa008** [comment]
>我们可以按照一定规则确定一组原创作者做为审核人。
可以考虑从作者 or start 的用户里随机抽取部分用户作为审核人。想法来自电影《12 Angry Men》

**Comment by linlinzzo** [comment]
@wa008 可以讨论一下，我个人是挺感兴趣的。

**Comment by wa008** [comment]
> @wa008 可以讨论一下，我个人是挺感兴趣的。

贡献一点点思路~~

需要判断一个博客是否达到「收录标准」时，从 star 的用户里随机找5-20个人，把待判断的博客发送给他们，让他们对「是否收录」给出自己的意见。
根据结果，再设定一个规则判断最终是否要收录。

举例：
假设一共发送给了 n 个人，x 个人回复同意收录，y 个人回复不同意，剩余未回复，可以设置最终是否收录的条件为以下之一：
1. x >= 3 && x > y 
2. x / n > 0.5

好处：
1. 从 star 用户里中随机抽样用户来决定是否最终收录，避免权利中心化。
2. star 用户群体大，审核的工作均摊给每个人，每个人的成本相对就小一些。
3. 让关心这个事的用户来决定是否收录，标准跟用法对齐。

坏处：
1. star 用户回复率不一定高

**Comment by linlinzzo** [comment]
@wa008 https://github.com/zh-blogs 负责一个中文博客地址库的专门维护工作，不妨下设一个小组讨论某博客是否符合标准？

**Comment by Ninjiaazz** [comment]
> 



> > @wa008 可以讨论一下，我个人是挺感兴趣的。
> 
> 贡献一点点思路~~
> 
> 需要判断一个博客是否达到「收录标准」时，从 star 的用户里随机找5-20个人，把待判断的博客发送给他们，让他们对「是否收录」给出自己的意见。 根据结果，再设定一个规则判断最终是否要收录。
> 
> 举例： 假设一共发送给了 n 个人，x 个人回复同意收录，y 个人回复不同意，剩余未回复，可以设置最终是否收录的条件为以下之一：
> 
> 1. x >= 3 && x > y
> 2. x / n > 0.5
> 
> 好处：
> 
> 1. 从 star 用户里中随机抽样用户来决定是否最终收录，避免权利中心化。
> 2. star 用户群体大，审核的工作均摊给每个人，每个人的成本相对就小一些。
> 3. 让关心这个事的用户来决定是否收录，标准跟用法对齐。
> 
> 坏处：
> 
> 1. star 用户回复率不一定高

不错，应当建立一个专门的审核群组，推荐加入者来一键加入此审核群组。

**Comment by linlinzzo** [comment]
@wa008 @Ninjiaazz 
https://github.com/orgs/zh-blogs/teams/blog-audit-team
专门为中文博客列表提供负责中文博客的判别和审核

**Comment by wa008** [comment]
> @wa008 https://github.com/zh-blogs 负责一个中文博客地址库的专门维护工作，不妨下设一个小组讨论某博客是否符合标准？

可以呀

**Comment by wa008** [comment]
> 



> @wa008 @Ninjiaazz https://github.com/orgs/zh-blogs/teams/blog-audit-team 专门为中文博客列表提供负责中文博客的判别和审核

链接404了

**Comment by linlinzzo** [comment]
> 链接404了

组内成员才看得到。

**Comment by linlinzzo** [comment]
via https://github.com/zh-blogs/zh-blog-criteria/issues

**Comment by linlinzzo** [comment]
move to https://github.com/BlogStandards as a todo, it will resolve this problem.
